### ISSUE TITLE
The structure is entirely wrong.

### ISSUE THREAD

**Issue by TRVPLVRD** [iamjawa/zork-py#1]
I suggest you look up how to develop a text adventure, and frankly the source to this looks terrible. You're not supposed to just get input then compare it to every possibly situation that can occur. You should get input, parse it (look for verbs, nouns) and then act accordingly.

**Comment by iamjawa** [comment]
I'm not going to act like a complete douche and disregard your comment because it's a negative one, I appreciate your advice because I have never heard of this method.

However, may I also add that this was completed as a school project within 5 days.

**Comment by iamjawa** [comment]
Feel free to rewrite this program yourself and contribute the results.

**Comment by Ksisky** [comment]
I see @TRVPLVRD  he is coming from. I think there should be a list of options or you should parse it. I might submit a pull request. I'm trying to learn python, this would be a good way to improve.

**Comment by iamjawa** [comment]
@Ksisky Fair enough - I wrote this program within a 5 day period for ICT coursework at school and had  pretty much no knowledge of Python at the time so this was the best I could do; I'd like to see a completed version of it though :)
