### ISSUE TITLE
raw_input not defined

### ISSUE THREAD

**Issue by Arsonomega** [iamjawa/zork-py#12]
I'm running this in Powershell if it makes a difference.

I'm learning python through Learn python 3 the hard way and in exercise 14 it tells me to find zork and adventure and play them.

This popped up when I first ran it.

>You are standing in an open field west of a white house, with a boarded front door.
>(A secret path leads southwest into the forest.)
>There is a Small Mailbox.
>Traceback (most recent call last):
>  File "D:\Pythonlearn\zork-py-1.3\zork.py", line 10, in <module>
>    first = raw_input(str("What do you do? "))
>NameError: name 'raw_input' is not defined

I replaced every instance of "raw_input" with "input' and it worked fine.

**Comment by iamjawa** [comment]
This will be using an older version of zork-py as all instances of "raw_input" were replaced in a newer version. The error you get is due to "raw_input" being deprecated in favour of "input" within Python 3. Hope this helps!
